namespace: labs-hs-test
app_name: dockerbuild-zap

build:
  NAME: "{{ app_name }}"
  SOURCE_REPOSITORY_URL: https://github.com/haithamshahin333/testing-containers.git
  SOURCE_REPOSITORY_REF: zap
  SOURCE_CONTEXT_DIR: build-docker-generic

openshift_cluster_content:
- object: Builds
  content:
  - name: "{{ app_name }}"
    template: "{{ inventory_dir }}/../.openshift/templates/docker-build-template.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ namespace }}"
    tags:
      - build
